Repository minjune8506/GeneticAvoidance, pull requests merged in 2022-05, with the labels that each got.

#6 Refact : Dodge Game 구조 변경
  dodge/dodge.py
  dodge/enemy.py
  dodge/game.py
  dodge/helpers.py
  dodge/player.py
Labels: refactor

#5 [#4] 신경망 초기 설계 완료
  dodge/game.py
  dodge/helpers.py
  dodge/network.py
  dodge/player.py
  genome.py
Labels: feature

#11 기능 추가 & 리팩토링
  dodge/enemy.py
  dodge/game.py
  dodge/helpers.py
  dodge/player.py
Labels: enhancement, feature, refactor
