Repository minjune8506/GeneticAvoidance, pull requests merged in 2022-06, with the labels that each got.

#15 test 기록
  dodge/enemy.py
  dodge/game.py
  dodge/generation.py
  dodge/helpers.py
  dodge/network.py
  dodge/player.py
  genome.py
Labels: enhancement

#14 Test
  dodge/.idea/runConfigurations.xml
  dodge/.idea/vcs.xml
  dodge/.idea/workspace.xml
  dodge/enemy.py
  dodge/game.py
  dodge/generation.py
  dodge/helpers.py
  dodge/network.py
  dodge/player.py
Labels: refactor

#16 Update README
  README.md
Labels: documentation

#17 마무리
  dodge/enemy.py
  dodge/game.py
  dodge/generation.py
  dodge/helpers.py
  dodge/network.py
  dodge/player.py
Labels: feature
